name: Deploy to production (GCP & Vercel)

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: "Force rewite of production branch (use ONLY if the previous release was a cherry-pick)"
        required: false
        default: false

jobs:
  merge_production:
    name: Merge to production
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for rebasing to work
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Fast-forward the production branch and trigger the GCP production deploy workflow
        run: |
          git fetch origin production
          git checkout production
          if [ "${{ github.event.inputs.force}}" == "true" ]; then
            git reset --hard origin/${{ github.ref_name }} 
            git push --force-with-lease
          else
            git merge --ff-only origin/${{ github.ref_name }}
            git push
          fi
